using System.Reflection;
using BepInEx.Logging;
using HarmonyLib;
using BepInEx;

namespace InscryptionExampleMod
{
    // PluginInfo is auto-generated by `BepInEx.PluginInfoProps`, So you don't have to manually put this in.
    [BepInPlugin(PluginInfo.PLUGIN_GUID, PluginInfo.PLUGIN_NAME, PluginInfo.PLUGIN_VERSION)]
    public class Plugin : BaseUnityPlugin
    {

        public static ManualLogSource logger;
        private static Harmony harmony;

        // This will only run once, when the plugin is loaded.
        private void Awake()
        {
            logger = Logger;
            logger.LogInfo("Hello, World!");
            // Patching Inscryption's methods using HarmonyX.
            // See also: https://github.com/BepInEx/HarmonyX/wiki/Basic-usage
            harmony = Harmony.CreateAndPatchAll(Assembly.GetExecutingAssembly(), PluginInfo.PLUGIN_GUID);
        }

        // Unpatch everything if we got unloaded.
        private void OnDestroy()
        {
            logger.LogInfo("Good bye, World...");
            harmony.UnpatchSelf();
        }
    }
}
